spring:
  application:
    name: springPractise
  datasource:
    url: jdbc:mysql://localhost:3306/stu
    username: root
    password: zhaolong
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  port: 8080